# Generated by Django 4.2.1 on 2023-05-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=250)),
                ('dob', models.DateField(max_length=250)),
                ('age', models.IntegerField()),
                ('gen', models.CharField(max_length=250)),
                ('ph', models.CharField(max_length=250, unique=True)),
                ('mail', models.TextField(blank=True, unique=True)),
                ('add', models.TextField(blank=True)),
                ('dept', models.CharField(max_length=250)),
                ('cou', models.CharField(max_length=250)),
                ('pur', models.CharField(max_length=250)),
                ('mat', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materials',
            },
        ),
    ]
